package my-namespcae:my-package;

interface my-interface {
  variant variant2enum-variant {
    variant-case-a(bool),
    variant-case-b,
  }
  enum variant2enum-enum {
    enum-case-a,
    enum-case-b,
    enum-case-c,
    enum-case-d,
  }
  enum enum2variant-enum {
    enum-case-a,
    enum-case-b,
    enum-case-c,
    enum-case-d,
  }
  variant enum2variant-variant {
    variant-case-a(bool),
    variant-case-b,
  }
}
