package my-namespcae:my-package;

interface my-interface {
  record my-record {
    field-a: f32,
    field-b: option<f32>,
    field-c: tuple<f32, f32>,
  }
  resource my-resource {
    my-method: func(param-a: bool, param-b: option<option<f32>>);
  }
  variant my-variant {
    case-a(bool),
    case-b(string),
  }
}
