package my-namespcae:my-package;

interface my-interface {
  record record2variant-record {
    field-a: f32,
    field-b: option<f32>,
    field-c: tuple<f32, f32>,
  }
  variant record2variant-variant {
    case-a(bool),
    case-b(string),
    field-a(f32),
    field-b(option<f32>),
    field-c(tuple<f32, f32>),
  }
  resource params2record-resource {
    params2record-method: func(case-a: bool, case-b: string);
  }
  record params2record-record {
    field-a: f32,
    field-b: option<f32>,
    field-c: tuple<f32, f32>,
    case-a: bool,
    case-b: string,
  }
  variant variant2params-variant {
    case-a(bool),
    case-b(string),
  }
  resource variant2params-resource {
    variant2params-method: func(case-a: bool, case-b: string);
  }
}
