package my-namespcae:my-package;

interface my-interface {
  record my-record {
    field-a: f32,
    field-b: option<f32>,
    field-c: tuple<f32, f32>,
    param-a: bool,
    param-b: option<option<f32>>,
  }
  resource my-resource {
    my-method: func(case-a: bool, case-b: string);
  }
  variant my-variant {
    case-a(bool),
    case-b(string),
    field-a(f32),
    field-b(option<f32>),
    field-c(tuple<f32, f32>),
  }
}
