package webidl:my-package-idl;

interface my-interface {
  record gpu-color-dict {
    r: f64,
    g: f64,
    b: f64,
    a: f64,
  }
  variant gpu-color-dict-or-list-f64 {
    gpu-color-dict(gpu-color-dict),
    list-f64(list<f64>),
  }
  type gpu-color = gpu-color-dict-or-list-f64;
}
