package my-namespace:my-package;

interface my-interface {
  enum my-enum {
    enum-case-a,
    enum-case-b,
  }
  flags my-flags {
    flag-a,
    flag-b,
    flag-c,
  }
  record my-record {
    field-a: string,
    field-b: u32,
    field-c: bool,
  }
  resource my-resource {
    constructor(x: s32);
    method-a: func() -> string;
    static-b: static func() -> bool;
  }
  variant my-variant {
    variant-case-a(bool),
    variant-case-b,
  }
  variant target-enum-variant {
    existing-case,
    enum-case-a,
    enum-case-b,
  }
  variant target-flags-variant {
    existing-case,
    flag-a,
    flag-b,
    flag-c,
  }
  enum target-record-enum {
    existing-case,
    field-a,
    field-b,
    field-c,
  }
  enum target-resource-enum {
    existing-case,
    method-a,
    static-b,
  }
  enum target-variant-enum {
    existing-case,
    variant-case-a,
    variant-case-b,
  }
}
