package my-namespcae:my-package;

interface my-interface {
  resource my-resource {
    get-param: func(a: bool, b: option<option<f32>>);
    get-result-anon: func() -> result<f32, bool>;
    get-result-named: func() -> (a: f32);
  }
  record my-record {
    get-field: list<f32>,
  }
  variant my-variant {
    get-case(option<tuple<bool, bool, option<list<f32>>, bool>>),
    other-case(u32),
  }
}
