package my-namespcae:my-package;

interface my-interface {
  record my-record {
    rename-new-name: string,
    retype: f32,
    added: option<string>,
    from-list-a: tuple<u32, f32>,
    from-list-b: string,
  }
}
